spring:
  application:
    name: Air Fitness
  datasource:
    url: jdbc:postgresql://localhost:5432/airfitdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true